env:
  es6: true
ignorePatterns:
  - dist
overrides:
  -
    files:
      - '*.cjs'
    extends:
      - '@alex-taxiera/eslint-config-cjs'
  -
    files:
      - '*.ts'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
      project:
        - ./tsconfig.json
    extends:
      - '@alex-taxiera/eslint-config-ts'
    rules:
      no-console:
        - error
        -
          allow:
            - error
            - warn
